#!/bin/sh /etc/rc.common
# persistent run @ startup: /etc/init.d/vpn enable
NAME=vpn_shepherd
PROG=/usr/sbin/vpn_shepherd
START=99
STOP=1

start() {
	# check for new config (after install) and fix the system config
	# if needed (this may force a reboot)
	if [ -f /usr/sbin/fix_config ] ; then
		fix_config
	fi

	# start primary service scripts
	(vpn_shepherd &) &
	(vpn_led &) &

	# if there is a report config start the script
	if [ -f /etc/config/vpn_report ] ; then
		(vpn_report &) &
	fi
}                 
 
stop() {          
	killall vpn_shepherd 2>/dev/null
	killall vpn_led 2>/dev/null
	killall vpn_report 2>/dev/null
}

restart() {
	stop
	start
}
